### ISSUE TITLE
Possible incorrect answer for "Which Kubernetes object is used to grant permissions to a user or group within a namespace?"

### ISSUE THREAD

**Issue by amimas** [thiago4go/kubernetes-security-kcsa-mock#2]
Hello,

My first issue in this repo. I'm currently studying for the KCSA cert. This repo is very helpful. Thanks for setting this up.

I feel the "correct answer" configured for question "Which Kubernetes object is used to grant permissions to a user or group within a namespace?" might be incorrect. Right now the correct answer is configured to be "Role".

https://github.com/thiago4go/kubernetes-security-kcsa-mock/blob/f5c531e37eae5b087b906cd708e345a7b6fbd43d/src/questions.js#L2915-L2927

Shouldn't the correct answer be "RoleBinding" instead of "Role"? My reasoning is that a "Role" only defines a set of permissions. The "RoleBinding" is what used for applying those permissions (or role) to users or groups. Kubernetes [docs has following definition](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebinding-and-clusterrolebinding):

> A role binding grants the permissions defined in a role to a user or set of users. It holds a list of subjects (users, groups, or service accounts), and a reference to the role being granted. A RoleBinding grants permissions within a specific namespace whereas a ClusterRoleBinding grants that access cluster-wide.

Defining a role doesn't really have any effect unless it's applied or used  by someone, right? Is there something in the question I'm not interpreting correctly?

**Comment by thiago4go** [comment]
Hi @amimas, thanks for your contribution. I agree that this answer is missleading. While a role defines permissions only when it is bound to a user or a set of users, it will actually grant them within a namespace. 

Would the following update make this a better question?

```
"id": 214,
  "question": "Which Kubernetes object is used to assign permissions within a namespace to a user or group?",
  "options": [
    "ClusterRole",
    "Role",
    "ClusterRoleBinding",
    "RoleBinding",
    "ServiceAccount"
  ],
  "correct_answers": [3],
  "explanation": "A 'RoleBinding' is used to grant the permissions defined in a 'Role' to a user, group, or service account within a specific namespace. While a 'Role' defines permissions, it is the 'RoleBinding' that assigns those permissions to subjects.",
  "question_type": "single-choice"
```

**Comment by amimas** [comment]
Hi @thiago4go - your update looks good to me. I went ahead and opened a PR with your suggestion.

I'm getting ready to take the KCSA cert exam. In your experience, are there questions in real exam that may not be defined clearly? Not sure how else to reach you. Appreciate if you could share any tips or suggestions.

And once again, really thankful to you for making these questions openly available instead of paid material.
