### ISSUE TITLE
Possible incorrect answer configured for "Which command lists all installed packages on a system using apt?"

### ISSUE THREAD

**Issue by amimas** [thiago4go/kubernetes-security-kcsa-mock#3]
Hi,

The question "Which command lists all installed packages on a system using apt?" is currently configured to be correct if `dpkg -l` is selected as the answer.

https://github.com/thiago4go/kubernetes-security-kcsa-mock/blob/f5c531e37eae5b087b906cd708e345a7b6fbd43d/src/questions.js#L3320-L3333

I feel that's incorrect answer because the question specifically asks about "using `apt`". The `dpkg` is not an alias or part of `apt` tool. So, the correct answer should be `apt list --installed`.

Happy to open a PR to fix this but wanted to open an issue to discuss first in case I'm mis-interpreting the question somehow. Could you please confirm?

**Comment by thiago4go** [comment]
Thanks @amimas 
Please feel free to opena PR, the correct answer should be `apt list --installed`
